###
GET http://localhost:8082/api/v1/products/lopes

###
POST http://localhost:8082/api/v1/products/lopes
Content-Type: application/json

{
  "name": "Product 1"
}

###
POST http://localhost:8082/api/v1/products
Content-Type: application/json

{
  "name": "lopes"
}