###
GET http://localhost:8082/api/v1/products/lopes

###
GET http://localhost:8082/api/v1/products/lopes/New Product

###
POST http://localhost:8082/api/v1/products/lopes
Content-Type: application/json

{
  "name": "New Product"
}

###
POST http://localhost:8082/api/v1/products
Content-Type: application/json

{
  "name": "lopes"
}